### ISSUE TITLE
Parse environment variables in the config.yaml file

### ISSUE THREAD

**Issue by ercanozkaya** [joomlatools/joomlatools-console#154]
In https://github.com/joomlatools/joomlatools-console/pull/132 we added support for adding a `~/.joomlatools/console/config.yaml` file as an override for default arguments.

Parse and replace the environment variables in this file so the following file could be used successfully: 
```yaml
globals:
  www: $APP_ROOT/sites
"site:create":
  options: $HOME/.joomlatools/console/site-configuration.yaml
```
